# Generated by Django 4.2 on 2024-05-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default='', max_length=600, null=True),
        ),
    ]
